### ISSUE TITLE
[Bug] Player cannot swim on the X/Z axis, and can only go up or down

### ISSUE THREAD

**Issue by StarlitSlays** [jack-zisa/CreoLib#4] opened 2023-05-02 14:45 UTC
I'd assume this is caused by the entity swim_speed attribute, however I don't know.

This bug was present constantly (across worlds/gamemodes/etc) and I had to go through each of my mods to find the specific cause. Eventually I isolated that CreoLib was the cause (my version was 1.19.4-0.0.1-alpha.20). 
Originally, I got CreoLib for great big world, however removed it as it was causing a bit of lag (possibly due to other WGen mods) but I forgot to remove CreoLib. After readding GBW, I can safely say that the issue is the library itself; the library still causes this bug even with GBW installed.

While it's a possibility, I only had 62 other mods (none of which affect water) so I doubt the issue was incompatibility.
The player can still move if the water is open, such as an ocean. This is only because the player bobs out of the water for a slight moment, but the bug returns as soon as they enter water (basically meaning you hardly move)

**A short summary of the bug:**
The CreoLib library causes issues, alone or with other mods/dependents (of CreoLib). The issue is that the player can go up and down at normal speeds, but moving horizontally/diagonally is either super slow or impossible. Water bodies with air 2 blocks tall above it are not affected, but only while outside of the water.

I believe the issue is swim_speed or something, as I have not changed any config files. This may have already been noticed or not, but better safe than sorry ❤️

**Comment by jack-zisa** [comment] 2023-05-04 04:54
The issue is swim_speed, and I actually only found out about this recently while testing new features! This should be fixed in [this commit](https://github.com/jack-zisa/CreoLib/commit/30e2c32f6d9060cb3899b28765d6b51e494704bf), but I'll test it out again just to make sure.
Unfortunately, Great Big World will be on the older version of Creo Lib until the next beta/release.

I appreciate the bug report; hopefully I can move this out of alpha soon so you and others can play it <3

**Comment by jack-zisa** [comment] 2023-05-04 06:08
Just tested and can confirm it works in the latest versions.

**Closed by jack-zisa** 2023-05-04 06:08 UTC
Labels: bug
